version: 2.1
executors:
  gopherjs:
    docker:
    - image: cimg/base:stable
    working_directory: ~/gopherjs

workflows:
  version: 2
  build_and_test:
    jobs:
    - build
    - gopherjs_tests:
        requires: 
          - build
    - gorepo_tests:
        requires: 
          - build

parameters:
  go_version:
    type: string
    default: "1.16.5"
  nvm_version:
    type: string
    default: "0.33.9"
  node_version:
    type: string
    default: "10.0.0"
  node_gyp_version:
    type: string
    default: "5.1.1"

jobs:
  build:
    executor: gopherjs
    steps:
    - setup_environment
    - checkout
    - install_deps
    - install_gopherjs
    - run:
        name: Check minified prelude
        command: |
          set -e
          go generate github.com/gopherjs/gopherjs/compiler/prelude
          diff -u <(echo -n) <(git status --porcelain)
    - run:
        name: Check gofmt
        command: diff -u <(echo -n) <(gofmt -d .)
    - run: 
        name: Check go vet
        command: |
          set -e  
          # Go package in root directory.
          go vet . 
          # All subdirectories except "doc", "tests", "node*".
          for d in */; do echo ./$d...; done | grep -v ./doc | grep -v ./tests | grep -v ./node | xargs go vet 
    - run:
        name: Check natives build tags
        command: diff -u <(echo -n) <(go list ./compiler/natives/src/...) # All those packages should have // +build js.
    - run:
        name: Smoke tests
        command: |
          gopherjs install -v net/http # Should build successfully.
          gopherjs test -v fmt log # Should catch problems with test execution and source maps.
    - run:
        name: go test ...
        command: |
          set +e
          # Run all tests except gorepo, which will be run separately in parallel.
          go test -v -race $(go list ./... | grep -v github.com/gopherjs/gopherjs/tests/gorepo) | tee /tmp/test-go.txt
          status="$?"
          # Convert test output into junit format for CircleCI.
          mkdir -p ~/test-reports/
          go-junit-report --full-class-name < /tmp/test-go.txt > ~/test-reports/go.xml
          exit "$status"
    - store_test_results:
        path: ~/test-reports/
    - run:
        name: TodoMVC in GOPATH mode
        command: |
          set -e
          export GO111MODULE=off
          export GOPATH=/tmp/gopath
          mkdir -p $GOPATH/src
          go get -v github.com/gopherjs/todomvc
          gopherjs build -v -o /tmp/todomvc_gopath.js github.com/gopherjs/todomvc
          gopherjs test -v github.com/gopherjs/todomvc/...
          find $GOPATH
    - run:
        name: TodoMVC in Go Modules mode
        command: |
          set -e  
          export GO111MODULE=on
          export GOPATH=/tmp/gomod
          mkdir -p $GOPATH/src
          cd /tmp
          git clone --depth=1 https://github.com/gopherjs/todomvc.git
          cd /tmp/todomvc
          gopherjs build -v -o /tmp/todomvc_gomod.js github.com/gopherjs/todomvc
          gopherjs test -v github.com/gopherjs/todomvc/...
          find $GOPATH
    - run:
        name: Compare GOPATH and Go Modules output
        command: diff -u <(sed 's/todomvc_gomod.js.map/todomvc_ignored.js.map/' /tmp/todomvc_gomod.js) <(sed 's/todomvc_gopath.js.map/todomvc_ignored.js.map/' /tmp/todomvc_gopath.js)
  
  gopherjs_tests:
    executor: gopherjs
    parallelism: 4
    steps:
    - setup_environment
    - checkout
    - install_deps
    - install_gopherjs
    - run:
        name: gopherjs test ...
        command: |
          set +e
          ulimit -s 10000
          PACKAGE_NAMES=$( \
            GOOS=js GOARCH=wasm go list std github.com/gopherjs/gopherjs/js/... github.com/gopherjs/gopherjs/tests/... \
            | grep -v -x -f .std_test_pkg_exclusions \
            | circleci tests split --split-by=timings --timings-type=classname \
          )
          gopherjs test -p 2 --minify -v --short $PACKAGE_NAMES \
            | tee /tmp/test-gopherjs.txt
          status="$?"
          set -e
          # Convert test output into junit format for CircleCI.
          mkdir -p ~/test-reports/
          go-junit-report --full-class-name < /tmp/test-gopherjs.txt > ~/test-reports/gopherjs.xml
          exit "$status"
    - store_test_results:
        path: ~/test-reports/

  gorepo_tests:
    executor: gopherjs
    parallelism: 4
    steps:
    - setup_environment
    - checkout
    - install_deps
    - install_gopherjs
    - run:
        name: Go Repository tests
        command: |
          go test -v github.com/gopherjs/gopherjs/tests/gorepo

commands:
  setup_environment:
    description: Set up Go, NVM and Node.js
    steps:
    - run:
        name: Install Go
        command: |
          cd /usr/local
          sudo rm -rf go
          curl "https://storage.googleapis.com/golang/go<< pipeline.parameters.go_version >>.linux-amd64.tar.gz" | sudo tar -xz
          echo 'export PATH="$PATH:/usr/local/go/bin:$HOME/go/bin"' >> $BASH_ENV
          echo 'export GO111MODULE=on' >> $BASH_ENV
          . $BASH_ENV
          go get -v github.com/nevkontakte/go-junit-report@forked # For CircleCI test reports.
    - run:
        name: Install NVM
        command: |
          git clone https://github.com/creationix/nvm $HOME/.nvm
          cd $HOME/.nvm && git checkout "v<< pipeline.parameters.nvm_version >>"
          echo 'export NVM_DIR="${HOME}/.nvm"' >> "${BASH_ENV}"
          echo '[ -s "${NVM_DIR}/nvm.sh" ] && \. "${NVM_DIR}/nvm.sh"' >> "${BASH_ENV}"
    - run:
        name: Install Node.js
        command: |
          nvm install "<< pipeline.parameters.node_version >>" && nvm alias default "<< pipeline.parameters.node_version >>"
          # Make nodejs able to require globally installed modules from any working path.
          echo export "NODE_PATH='$(npm root --global)'" >> "${BASH_ENV}"
  install_deps:
    description: Install Go and Node dependency packages
    steps:
    - run:
        name: Install required Node.js packages
        command: |
          npm install # Install our (dev) dependencies from package.json.
          npm install --global source-map-support # Required by standard library tests.
          npm install --global "node-gyp@<< pipeline.parameters.node_gyp_version >>"
          (cd node-syscall && node-gyp rebuild && mkdir -p $NODE_PATH && cp build/Release/syscall.node "${NODE_PATH}/syscall.node")
          echo 'export SOURCE_MAP_SUPPORT=true' >> $BASH_ENV
    - run: 
        name: Install required Go packages
        command: go get -t -d -v ./...
  install_gopherjs:
    description: Install GopherJS
    steps:
    - run:
        name: Install GopherJS
        command: go install -v

